socialproject/accounts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'userprofile', views.UserProfileView, 'userprofile')

app_name = 'accounts'

urlpatterns = [
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', views.ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', views.AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', views.RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/followers', views.ListFollowers.as_view(), name='followers-list'),
    path('search/', views.UserSearch.as_view(), name='profile-search'),
    path('notification/<int:notification_pk>/post/<int:object_pk>', views.PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/follow/<int:object_pk>', views.FollowNotification.as_view(), name='follow-notification'),
    path('notification/delete/<int:notification_pk>', views.RemoveNotification.as_view(), name='notification-delete'),
    path('notification/<int:notification_pk>/thread/<int:object_pk>', views.ThreadNotification.as_view(), name='thread-notification'),
    path('inbox/', views.ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread', views.CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', views.ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', views.CreateMessage.as_view(), name='create-message'),
    path('api/', include(router.urls)),
]

# if settings.DEBUG: #add this
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialproject/posts/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
    path('edit/<int:pk>/', views.EditPost.as_view(), name='edit'),
    path('like/<int:pk>/', views.AddLike.as_view(), name='like'),
    path('<int:post_pk>/comment/reply/<int:pk>/', views.CommentReplyView.as_view(), name='comment-reply'),
    path('<int:post_pk>/comment/reply/', views.PostReplyView.as_view(), name='post-reply'),
    path('<int:post_pk>/comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment-delete'),
    path('<int:post_pk>/comment/like/<int:pk>/', views.AddCommentLike.as_view(), name='comment-like'),
    path('<int:pk>/share', views.SharedPostView.as_view(), name='share-post'),
    path('explore/', views.Explore.as_view(), name='explore'),
]
# if settings.DEBUG: #add this
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialproject/accounts/models.py
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist

class UserProfile(models.Model):
    ''' Model for user profiles '''
    user = models.OneToOneField(User, primary_key=True, verbose_name='user',
        related_name='profile', on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    picture = models.ImageField(upload_to='uploads/profile_pictures/',
        default='uploads/profile_pictures/default.png', blank=True)
    followers = models.ManyToManyField(User, blank=True,
        related_name='followers')

    def __str__(self):
        return f"{self.user} profile"

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    ''' Creates user profile instance on registration '''
    try:
        instance.profile.save()
    except ObjectDoesNotExist:
        UserProfile.objects.create(user=instance)

class Notification(models.Model):
    ''' Model for notifications, notification types:
    1 = Like, 2 = Comment, 3 = Follow, 4 = DMs '''
    notification_type = models.IntegerField(null=True, blank=True)
    to_user = models.ForeignKey(User, related_name='notification_to',
        on_delete=models.CASCADE, null=True)
    from_user = models.ForeignKey(User, related_name='notification_from',
        on_delete=models.CASCADE, null=True)
    post = models.ForeignKey('posts.Post', on_delete=models.CASCADE,
        related_name='+', blank=True, null=True)
    comment = models.ForeignKey('posts.Comment', on_delete=models.CASCADE,
        related_name='+', blank=True, null=True)
    thread = models.ForeignKey('ThreadModel', on_delete=models.CASCADE,
        related_name='+', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    user_has_seen = models.BooleanField(default=False)

# Sending and receiving direct messages
class ThreadModel(models.Model):
    ''' Model for all messages between two users '''
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    has_unread = models.BooleanField(default=False)

class MessageModel(models.Model):
    ''' Model for individual message '''
    thread = models.ForeignKey('ThreadModel', related_name='+',
        on_delete=models.CASCADE, blank=True, null=True)
    sender_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    receiver_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='+')
    body = models.CharField(max_length=1000)
    image = models.ImageField(upload_to='uploads/message_photos', blank=True, null=True)
    date = models.DateTimeField(default=timezone.now)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return self.body

# Contact page
class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email

socialproject/accounts/forms.py
''' Forms for our messages '''
from django import forms
from .models import MessageModel, UserProfile, Contact

class ThreadForm(forms.Form):
    ''' Form to create a thread '''
    username = forms.CharField(label='', max_length=100,
        widget=forms.TextInput(attrs={'placeholder':'Username',
        'class': 'is-warning is-rounded'}))

class MessageForm(forms.ModelForm):
    ''' Form for the individual message '''
    body = forms.CharField(label='', max_length=1000,
        widget=forms.TextInput(attrs={'placeholder':'Say something',
        'class':'is-warning is-rounded mb-5'}))
    image = forms.ImageField(label='Send an Image', required=False,)

    class Meta:
        model = MessageModel
        fields = ['body', 'image']

class ProfileEditForm(forms.ModelForm):
    bio = forms.CharField(required=False,label='Bio:', max_length=500,
        widget=forms.Textarea(attrs={'rows': '10',
        'class':'text-area is-warning mb-5'}))

    location = forms.CharField(required=False,label='Location:', max_length=100,
        widget=forms.TextInput(attrs={'placeholder':'Location',
        'class':'is-warning mb-5'}))

    picture = forms.ImageField(required=False,
        widget=forms.FileInput(attrs={'class':'file-input has-name'}))

    class Meta:
        model = UserProfile
        fields = ['bio','location','picture']

class ContactForm(forms.ModelForm):
    email = forms.CharField(label='', max_length=100,
        widget=forms.TextInput(attrs={'placeholder':'Your email',
        'class': 'is-warning mb-3'}))

    subject = forms.CharField(label='', max_length=100,
        widget=forms.TextInput(attrs={'placeholder':'Subject ',
        'class': 'is-warning mb-3'}))

    message = forms.CharField(label='', max_length=500,
        widget=forms.Textarea(attrs={'placeholder':'Message','rows': '10',
        'class':'text-area is-warning mb-3'}))

    class Meta:
        model = Contact
        fields = '__all__'

socialproject/accounts/views.py
''' Views for accounts '''
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import redirect
from django.db.models import Q
from django.http import HttpResponse
from posts.models import Post
from rest_framework import viewsets
from .serializers import ProfileSerializer
from .models import UserProfile, Notification, ThreadModel, MessageModel
from .forms import ThreadForm, MessageForm, ProfileEditForm

class ProfileView(View):
    ''' View for profiles '''
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        user = profile.user
        posts = Post.objects.filter(author=user).order_by('-created_at')
        followers = profile.followers.all()
        follower_count = len(followers)

        if follower_count == 0:
            is_following = False

        for follower in followers:
            if follower == request.user:
                is_following = True
                break
            else:
                is_following = False


        context = {
            'user': user,
            'profile': profile,
            'posts': posts,
            'is_following': is_following,
            'follower_count': follower_count,
        }

        return render(request, 'accounts/profile.html', context)

class ProfileEditView(LoginRequiredMixin, UpdateView):
    ''' View for editing profiles '''
    model = UserProfile
    form_class = ProfileEditForm
    template_name = 'accounts/profile_edit.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('accounts:profile', kwargs={'pk': pk})

class AddFollower(LoginRequiredMixin, View):
    ''' View for following a user '''
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        profile.followers.add(request.user)
        notification = Notification.objects.create(notification_type=3,
            from_user=request.user, to_user=profile.user)

        return redirect('accounts:profile', pk=profile.pk)

class RemoveFollower(LoginRequiredMixin, View):
    ''' View for unfollowing a user '''
    def post(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        profile.followers.remove(request.user)

        return redirect('accounts:profile', pk=profile.pk)

class UserSearch(View):
    ''' View for searching user profiles '''
    def get(self, request, *args, **kwargs):
        query = self.request.GET.get('query')
        if query is None:
            return render(request, 'accounts/search.html')

        else:
            profile_list = UserProfile.objects.filter(
                Q(user__username__icontains=query)
            )
            context = {
                'profile_list': profile_list,
                'query': query,
            }
            return render(request, 'accounts/search.html',context)

class ListFollowers(View):
    ''' View for listing a users followers '''
    def get(self, request, pk, *args, **kwargs):
        profile = UserProfile.objects.get(pk=pk)
        followers = profile.followers.all()
        context = {
            'profile': profile,
            'followers': followers,
        }
        return render(request, 'accounts/followers_list.html', context)

class PostNotification(View):
    ''' View for post notifications '''
    def get(self, request, notification_pk, object_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        post = Post.objects.get(pk=object_pk)
        notification.user_has_seen = True
        notification.save()
        return redirect('posts:single', pk=object_pk, username=post.author)

class FollowNotification(View):
    ''' View for follow notifications '''
    def get(self, request, notification_pk, object_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        profile = UserProfile.objects.get(pk=object_pk)
        notification.user_has_seen = True
        notification.save()
        return redirect('accounts:profile', pk=object_pk)

class ThreadNotification(View):
    def get(self, request, notification_pk, object_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        thread = ThreadModel.objects.get(pk=object_pk)

        notification.user_has_seen = True
        notification.save()

        return redirect('accounts:thread', pk=object_pk)

class RemoveNotification(View):
    ''' View for removing notifications '''
    def delete(self, request, notification_pk, *args, **kwargs):
        notification = Notification.objects.get(pk=notification_pk)
        notification.user_has_seen = True
        notification.save()
        return HttpResponse('Success', content_type='text/plain')

class CreateThread(View):
    ''' View for creating threads '''
    def get(self, request, *args, **kwargs):
        ''' Displays the form to enter a username '''
        form = ThreadForm()
        context = {
            'form': form
        }
        return render(request, 'accounts/create_thread.html', context)

    def post(self, request, *args, **kwargs):
        ''' Handles creation of thread by grabbing form and see if user matches
        that username. If there is a user, it will check to see if a thread
        exists between the two users already, if there is it will open that
        thread up. If no thread, it will create and redirect to thread. '''
        form = ThreadForm(request.POST)
        username = request.POST.get('username')
        try:
            receiver = User.objects.get(username=username)
            if ThreadModel.objects.filter(user=request.user, receiver=receiver).exists():
                thread = ThreadModel.objects.filter(user=request.user, receiver=receiver)[0]
                return redirect('accounts:thread', pk=thread.pk)
            elif ThreadModel.objects.filter(user=receiver, receiver=request.user).exists():
                thread = ThreadModel.objects.filter(user=receiver, receiver=request.user)[0]
                return redirect('accounts:thread', pk=thread.pk)

            if form.is_valid():
                thread = ThreadModel(
                    user=request.user,
                    receiver=receiver
                )
                thread.save()
                return redirect('accounts:thread', pk=thread.pk)
        except:
            messages.error(request, f'Sorry! cannot find "{username}" 😭')
            return redirect('accounts:create-thread')

class ListThreads(View):
    ''' View which acts as a inbox to see all conversations '''
    def get(self, request, *args, **kwargs):
        ''' Grabs all threads where the logged in user is either the sending
        user or receiving user '''
        threads = ThreadModel.objects.filter(Q(user=request.user) | Q(receiver=request.user))
        context = {
            'threads': threads
        }
        return render(request, 'accounts/inbox.html', context)

class CreateMessage(View):
    ''' View to create message then redirect back to ThreadView '''
    def post(self, request, pk, *args, **kwargs):
        form = MessageForm(request.POST, request.FILES)
        thread = ThreadModel.objects.get(pk=pk)
        if thread.receiver == request.user:
            receiver = thread.user
        else:
            receiver = thread.receiver

        if form.is_valid():
            message = form.save(commit=False)
            message.thread = thread
            message.sender_user = request.user
            message.receiver_user = receiver
            message.save()

        notification = Notification.objects.create(
            notification_type=4,
            from_user=request.user,
            to_user=receiver,
            thread=thread
        )

        return redirect('accounts:thread', pk=pk)

class ThreadView(View):
    ''' View to show all messages in a thread and displays a form at the
    bottom to send a new message '''
    def get(self, request, pk, *args, **kwargs):
        form = MessageForm()
        thread = ThreadModel.objects.get(pk=pk)
        message_list = MessageModel.objects.filter(thread__pk__contains=pk)
        context = {
              'thread': thread,
              'form': form,
              'message_list': message_list
        }
        return render(request, 'accounts/thread.html', context)

class UserProfileView(viewsets.ModelViewSet):
    serializer_class = ProfileSerializer
    queryset = UserProfile.objects.all()

socialproject/accounts/templates/accounts/create_thread.html
{% extends "base.html" %}

{% load bulma_tags %}

{% block title %}<title>Plume - Start a Conversation</title>{% endblock %}

{% block content %}
<div class="section">
  <h5 class="title has-text-light tricks fade-up">Start a Conversation!</h5>
  <a href="{% url 'accounts:inbox' %}" class="button">Return to convos</a>
  <div class="column is-half mt-3 mb-5">
    {{ query }}
    <form method="POST">
      {% csrf_token %}
      <p>Enter the full username to whom you wish to message</p>
      {{ form | bulma }}

      {% if messages %}
        {% for message in messages %}
          {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <div class="notification is-warning my-3">
            <button class="delete" onclick="this.parentElement.style.display='none'"></button>
            {{ message }}
          </div>
          {% endif %}
        {% endfor %}
      {% endif %}

      <button type="submit" class="button mt-5">Chat!</button>
    </form>
  </div>
</div>
{% endblock content %}

socialproject/accounts/templates/accounts/profile.html
{% extends "base.html" %}

{% load bulma_tags %}

{% block title %}<title>Plume - @{{ profile.user }}'s profile</title>{% endblock %}

{% block content %}
<div class="section">
  <!-- Profile card -->
  <div class="card">
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-128x128 is-mobile is-square">
            <img src="{{ profile.picture.url }}" class="is-rounded"/>
          </figure>
        </div>
        <div class="media-content mt-5">
          <p class="title is-3 has-text-light is-size-4-mobile">@{{ profile.user }}</p>
          {% if profile.location %}
          <p class="subtitle is-6 is-size-6-mobile"><i class="material-icons has-text-warning">place</i> <em>{{ profile.location }}</em></p>
          {% endif %}
          <a href="{% url 'accounts:followers-list' profile.pk%}" class="has-text-warning">Followers: {{ follower_count }}</a>

          {% if request.user.is_authenticated %}
            {% if request.user.is_superuser %}
              <a href="{% url 'accounts:profile-edit' profile.pk %}" class="has-text-warning">
                <i class="material-icons">edit</i>
              </a>
            {% elif profile.user == request.user %}
              <a href="{% url 'accounts:profile-edit' profile.pk %}" class="has-text-warning">
                <i class="material-icons">edit</i>
              </a>
            {% endif %}
          {% endif %}

        </div>
      </div>

      <div class="content">
        {% if profile.bio %}
        <p>bio: {{ profile.bio }}</p>
        {% endif %}
        {% if request.user.is_authenticated %}
        <div class="level">
            <a href="{% url 'accounts:create-thread' %}" method="post">
              <button class="button mr-2" type="submit" value="{{ profile.user }}">
                Message&nbsp<span class="material-icons">message</span>
              </button>
            </a>
            {% if is_following %}
            <form class="level-item level-left" method="POST" action="{% url 'accounts:remove-follower' profile.pk %}">
              {% csrf_token %}
              <button class="button" type=submit>Unfollow</button>
            </form>
            <em class="has-text-light">You are following {{ user }}</em>
            {% else %}
            <form class="level-item level-left" method="POST" action="{% url 'accounts:add-follower' profile.pk %}">
              {% csrf_token %}
              <button class="button" type=submit>Follow&nbsp <span class="material-icons">person_add</span></button>
            </form>
            {% endif %}
        </div>

        {% endif %}
      </div>
    </div>
  </div>

  <!-- Post history -->
  <h1 class="title has-text-light mt-5">Post history</h1>

  {% for post in posts %}
    {% include "posts/_post.html" %}
  {% endfor %}
</div>
{% endblock %}

socialproject/accounts/templates/accounts/search.html
{% extends "base.html" %}

{% load bulma_tags %}
{% load static %}

{% block title %}<title>Plume - User Search</title>{% endblock %}

{% block content %}
<div class="section">
  {% if query == None %}
  <h1 class="title has-text-light tricks fade-up">User Search</h1>
  {% else %}
  <h1 class="title has-text-light tricks fade-up">Search results for "{{ query }}"</h1>
  {% endif %}
  <div class="columns is-centered">
    <div class="column">
      <form class="has-text-light p-3 mb-5" method="GET" action="{% url 'accounts:profile-search' %}">
        <div class="field has-addons">
          <div class="control">
            <input class="input is-rounded" type="text" name='query' value="{{ request.GET.query }}" placeholder="Search for user">
          </div>
          <div class="control">
            <button class="button is-warning is-rounded" type="submit">
              <span class="material-icons">person_search</span>
            </button>
          </div>
        </div>
      </form>
      {% for profile in profile_list %}

      <div class="card my-5">
        <div class="card-content">
          <div class="media">
            <div class="media-left">
              <a href="{% url 'accounts:profile' profile.pk %}">
                  <figure class="image is-96x96 is-square is-mobile">
                    <img src="{{ profile.picture.url }}" class="is-rounded"/>
                  </figure>
              </a>
            </div>
            <div class="media-content">
              <p class="title is-4"><a class="has-text-warning is-size-5-mobile" href="{% url 'accounts:profile' profile.pk %}">@{{ profile.user }}
              {{ is_following }}</a></p>
              {% if profile.location %}
              <p class="subtitle is-6 mb-2"><i class="material-icons">place</i>&nbsp{{ profile.location }}</p>
              {% endif %}
              <p class="subtitle is-6">Followers: {{ profile.followers.all.count }}</p>
            </div>
          </div>

          <div class="content">
            {% if is_following %}
            <form method="POST" action="{% url 'accounts:remove-follower' profile.pk %}">
              {% csrf_token %}
              <button class="button" type=submit>Unfollow</button>
            </form>
            <em class="has-text-light">You are following {{ user }}</em>
            {% else %}
            <form method="POST" action="{% url 'accounts:add-follower' profile.pk %}">
              {% csrf_token %}
              <button class="button" type=submit>Follow</button>
            </form>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    <div class="column is-half p-5 m-5">
      <figure class="image p-5">
        <img src="{% static 'images/pof-pof/Searching.png' %}">
      </figure>
    </div>
  </div>


</div>
{% endblock %}

socialproject/accounts/templates/accounts/show_notifications.html
<!-- Small bug: empty dropdown content on alerts -->
<div class="dropdown is-hoverable" id="notification-container">
  <div class="dropdown-trigger">
    <div aria-haspopup="true" aria-controls="dropdown-menu">
      <i class="material-icons">notifications_active</i>
      <span onclick="showNotifications()">&nbsp{{ notifications.count }}</span>
    </div>
  </div>
  <div class="dropdown-menu" id="dropdown-menu" role="menu">

    <div class="dropdown-content py-0">
    {% for notification in notifications %}
      {% if notification.post %}
          {% if notification.notification_type == 1 %}
          <div class="dropdown-item">
              <a class="has-text-light" href="{% url 'accounts:post-notification' notification.pk notification.post.pk %}">@{{ notification.from_user }} liked your post</a>
              <a onclick="removeNotification(`{% url 'accounts:notification-delete' notification.pk %}`, `{{ request.path }}`)"><button class="delete is-small"></button></a>
          </div>
          {% elif notification.notification_type == 2 %}
          <div class="dropdown-item">
              <a class="has-text-light" href="{% url 'accounts:post-notification' notification.pk notification.post.pk %}">@{{ notification.from_user }} commented on your post</a>
              <a onclick="removeNotification(`{% url 'accounts:notification-delete' notification.pk %}', '{{ request.path }}')"><button class="delete is-small"></button></a>
          </div>
          {% endif %}
      {% elif notification.comment %}
          {% if notification.notification_type == 1 %}
          <div class="dropdown-item">
              <a class="has-text-light" href="{% url 'accounts:post-notification' notification.pk notification.comment.post.pk %}">@{{ notification.from_user }} liked your comment</a>
              <a onclick="removeNotification(`{% url 'accounts:notification-delete' notification.pk %}`, `{{ request.path }}`)"><button class="delete is-small"></button></a>
          </div>
          {% endif %}
          {% if notification.notification_type == 2 %}
          <div class="dropdown-item">
              <a class="has-text-light" href="{% url 'accounts:post-notification' notification.pk notification.comment.post.pk %}">@{{ notification.from_user }} replied to your comment</a>
              <a onclick="removeNotification(`{% url 'accounts:notification-delete' notification.pk %}`, `{{ request.path }}`)"><button class="delete is-small"></button></a>
          </div>
          {% endif %}
        {% elif notification.thread %}
  				<div class="dropdown-item">
  					<a class="has-text-light" href="{% url 'accounts:thread-notification' notification.pk notification.thread.pk %}">@{{ notification.from_user }} sent you a message</a>
  					<a onclick="removeNotification(`{% url 'accounts:notification-delete' notification.pk %}`, `{{ request.path }}`)"><button class="delete is-small"></button></a>
  				</div>
  			{% else %}
      <div class="dropdown-item">
          <a class="has-text-light" href="{% url 'accounts:follow-notification' notification.pk notification.from_user.profile.pk %}">@{{ notification.from_user }} has started following you</a>
          <a onclick="removeNotification(`{% url 'accounts:notification-delete' notification.pk %}`, `{{ request.path }}`)"><button class="delete is-small"></button></a>
      </div>
      {% endif %}

    {% endfor %}
    </div>
  </div>

</div>

socialproject/accounts/templates/accounts/thread.html
{% extends "base.html" %}

{% load bulma_tags %}

{% block title %}<title>Plume - Convo with @{{ thread.receiver }}</title>{% endblock %}

{% block content %}

<div class="section">
	<!-- Sender/Receiver card title -->
	<div class="card p-3 has-text-light title">
		{% if thread.receiver == request.user %}
		<!-- Thread user -->
		<div class="level is-inline-flex">
			<figure class="image is-64x64 level-left">
				<img src="{{ thread.user.profile.picture.url }}" alt="{{ thread.user }}">
			</figure>
			<a class="has-text-light level-item level-left tricks fade-up" href="{% url 'accounts:profile' thread.user.pk %}">&nbsp&nbsp@{{ thread.user }} </a>
		</div>
		{% else %}
		<!-- Thread receiver -->
		<div class="level is-inline-flex">
			<figure class="image is-64x64 level-left">
				<img src="{{ thread.receiver.profile.picture.url }}" alt="{{ thread.receiver }}">
			</figure>
			<a class="has-text-light level-item level-left tricks fade-up" href="{% url 'accounts:profile' thread.receiver.pk %}">&nbsp&nbsp@{{ thread.receiver }}</a>
		</div>
		{% endif %}
	</div>

	<!-- If No Messages -->
	{% if message_list.all.count == 0 %}
	<div class="my-5">
			<em>No Messages</em>
	</div>
	{% endif %}

	<!-- Threads -->
	{% for message in message_list %}
		<!-- Senders message -->
		{% if message.sender_user == request.user %}
		<div class="my-1">
			{% if message.image %}
			<div>
				<span class="is-size-7" style="float: right">{{ message.date|date:"j/n" }} - {{ message.date|time:"P" }}</span>
				<img src="{{ message.image.url }}" class="message-image mb-2 mr-1" style="float: right" />
			</div>
			{% endif %}
			<div class="my-3 has-text-right" style="clear: right">
				<p class="tag is-warning is-large">{{ message.body }}</p>
				<span class="is-size-7">{{ message.date|date:"j/n" }} - {{ message.date|time:"P" }}</span>
			</div>
		</div>
			<!-- Receivers message -->
			{% elif message.receiver_user == request.user %}
				{% if message.image %}
					<span class="is-size-7">{{ message.date|date:"j/n" }} - {{ message.date|time:"P" }}</span>
					<img src="{{ message.image.url }}" class="message-image" />
				{% endif %}
				<div class="my-3">
					<span class="is-size-7">{{ message.date|date:"j/n" }} - {{ message.date|time:"P" }}</span>
					<p class="tag is-warning is-light is-large">{{ message.body }}</p>
				</div>
			{% endif %}
	{% endfor %}

	<!-- Message form -->
		<div class="card mt-5 p-5">
			<form method="POST" action="{% url 'accounts:create-message' thread.pk %}" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form | bulma }}
				<button class="button mt-3" type="submit">Send Message</button>
			</form>
		</div>
	</div>
{% endblock content %}