advanced/learning_cbv/basic_app/urls.py
from django.urls import path, re_path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    re_path(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    re_path(r'^create/$',views.SchoolCreateView.as_view(),name='create'),
    re_path(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    re_path(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
]

advanced/learning_cbv/learning_cbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.IndexView.as_view()),
    path('basic_app/',include('basic_app.urls',namespace='basic_app'))
]

advanced/learning_cbv/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('basic_app:detail', kwargs={'pk':self.pk})

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advanced/learning_cbv/basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, TemplateView,
                                ListView, DetailView,
                                CreateView, UpdateView,
                                DeleteView)
from django.http import HttpResponse
from django.urls import reverse_lazy
from . import models # . = look at CWD

# CLASS BASED VIEWS

# class CBView(View):
#     def get(self,request):
#         return HttpResponse('Class based views are cool!')

class IndexView(TemplateView):
    template_name = 'index.html'

    # def get_context_data(self,**kwargs): # keyword arguments
    #     context = super().get_context_data(**kwargs)
    #     context['injectme'] = 'BASIC INJECTION'
    #     return context

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','principal','location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('basic_app:list') # wait until success

advanced/learning_cbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <title>Base</title>
  </head>
  <body style="background-color:#2A3439;"> 

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'basic_app:list' %}">Schools</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
            <a class="nav-link" href="#">Blank</a>
        </div>
      </div>
    </nav>

    <div class="container py-4">
      <div class="p-5 mb-4 text-white bg-dark rounded-3">
        <div class="container-fluid py-5">
          {% block body_block %}
          {% endblock %}
        </div>
      </div>
    </div>

  </body>
</html>

advanced/learning_cbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1>Delete {{school.name}}?</h1>
  <form method="post">
    {% csrf_token %}
    <button type="submit" name="button" class="btn btn-danger">Delete</button>
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
  </form>
{% endblock %}

advanced/learning_cbv/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1 class="display-5 fw-bold">This is a <em>detailed</em> list of {{school_detail.name}}</h1>
  <h3>School details:</h3>
  <p class="fs-5">Name: {{school_detail.name}}</p>
  <p class="fs-5">Principal: {{school_detail.principal}}</p>
  <p class="fs-5">Location: {{school_detail.location}}</p>
  <h3>Students:</h3>

  {% for student in school_detail.students.all %}
    <p class="fs-5">{{student.name}} who is {{student.age}} years old.</p>
  {% endfor %}

  <p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>


{% endblock %}

advanced/learning_cbv/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1>
    <!-- Checks if instance of primary key exists -->
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
  </h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

advanced/learning_cbv/basic_app/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
  <h1 class="display-5 fw-bold">Welcome to a list of all the schools</h1>
    <ol>
      {% for school in schools %}
      <h2 class="fs-4"><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
      {% endfor %}
    </ol>
{% endblock %}

advanced/learning_cbv/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <title>Base</title>
  </head>
  <body>
    <div class="container-xl pt-1">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

advanced/learning_cbv/templates/index.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
    <h1 class="display-5 fw-bold">Welcome to the home page!</h1>
{% endblock %}