socialproject/accounts/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'userprofile', views.UserProfileView, 'userprofile')

app_name = 'accounts'

urlpatterns = [
    path('profile/<int:pk>/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', views.ProfileEditView.as_view(), name='profile-edit'),
    path('profile/<int:pk>/followers/add', views.AddFollower.as_view(), name='add-follower'),
    path('profile/<int:pk>/followers/remove', views.RemoveFollower.as_view(), name='remove-follower'),
    path('profile/<int:pk>/followers', views.ListFollowers.as_view(), name='followers-list'),
    path('search/', views.UserSearch.as_view(), name='profile-search'),
    path('notification/<int:notification_pk>/post/<int:object_pk>', views.PostNotification.as_view(), name='post-notification'),
    path('notification/<int:notification_pk>/follow/<int:object_pk>', views.FollowNotification.as_view(), name='follow-notification'),
    path('notification/delete/<int:notification_pk>', views.RemoveNotification.as_view(), name='notification-delete'),
    path('notification/<int:notification_pk>/thread/<int:object_pk>', views.ThreadNotification.as_view(), name='thread-notification'),
    path('inbox/', views.ListThreads.as_view(), name='inbox'),
    path('inbox/create-thread', views.CreateThread.as_view(), name='create-thread'),
    path('inbox/<int:pk>/', views.ThreadView.as_view(), name='thread'),
    path('inbox/<int:pk>/create-message/', views.CreateMessage.as_view(), name='create-message'),
    path('api/', include(router.urls)),
]

# if settings.DEBUG: #add this
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialproject/groups/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    re_path(r'posts/in/(?P<slug>[-\w]+)/$',views.SingleGroup.as_view(),name='single'),
    re_path(r'join/(?P<slug>[-\w]+)/$',views.JoinGroup.as_view(),name='join'),
    re_path(r'leave/(?P<slug>[-\w]+)/$',views.LeaveGroup.as_view(),name='leave'),
    re_path(r'edit/(?P<slug>[-\w]+)/', views.EditGroup.as_view(), name='edit'),
    re_path(r'delete/(?P<slug>[-\w]+)/',views.DeleteGroup.as_view(),name='delete'),
]

# if settings.DEBUG: #add this
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialproject/posts/urls.py
from django.urls import path, re_path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'posts'

urlpatterns = [
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/<str:username>/<int:pk>/',views.PostDetail.as_view(),name='single'),
    path('delete/<int:pk>/',views.DeletePost.as_view(),name='delete'),
    path('edit/<int:pk>/', views.EditPost.as_view(), name='edit'),
    path('like/<int:pk>/', views.AddLike.as_view(), name='like'),
    path('<int:post_pk>/comment/reply/<int:pk>/', views.CommentReplyView.as_view(), name='comment-reply'),
    path('<int:post_pk>/comment/reply/', views.PostReplyView.as_view(), name='post-reply'),
    path('<int:post_pk>/comment/delete/<int:pk>/', views.CommentDeleteView.as_view(), name='comment-delete'),
    path('<int:post_pk>/comment/like/<int:pk>/', views.AddCommentLike.as_view(), name='comment-like'),
    path('<int:pk>/share', views.SharedPostView.as_view(), name='share-post'),
    path('explore/', views.Explore.as_view(), name='explore'),
]
# if settings.DEBUG: #add this
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialproject/posts/forms.py
from django import forms
from .models import Post, Comment
from groups.models import Group

class PostForm(forms.ModelForm):
    message = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '6', 'placeholder':'Say something!',
            'class': 'control is-warning textarea mb-3'
            })
        )

    image = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'multiple': True,
            })
        )

    group = forms.ModelChoiceField(
        queryset=Group.objects.all(),
        label='Group',
        required=False,
        widget=forms.Select(attrs={
            'class': 'mb-3 control'
            })
        )

    class Meta:
        model = Post
        fields = ['message','group','image']

class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={'rows': '3','placeholder':'Got something to comment?',
            'class': 'is-warning textarea'}
        ))
    class Meta:
        model = Comment
        fields = ['comment']

class ShareForm(forms.Form):
    ''' Handles ability for user to enter text with a shared post '''
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3','placeholder':'Got something to share?',
            'class': 'is-warning textarea'
            })
        )

class ExploreForm(forms.Form):
    ''' Search form to filter explore page by other tags
    allowing users to search for posts with specific tags '''
    query = forms.CharField(
    label='',
    widget=forms.TextInput(attrs={'placeholder':'Enter hashtag',
        'class': 'is-warning is-rounded'})
    )

socialproject/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone

from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404, HttpResponseRedirect

from django.contrib import messages
from django.contrib.auth.models import User

from braces.views import SelectRelatedMixin

from accounts.models import Notification
from .models import Post, Comment, Image, Tag
from .forms import PostForm, CommentForm, ShareForm, ExploreForm

# Create your views here.
class PostList(LoginRequiredMixin,generic.View):
    def get(self, request, *args, **kwargs):
        # shows only posts from users that are followed
        feed_posts = Post.objects.filter(
            author__profile__followers__in=[request.user.id]
        ).order_by('-created_at')
        # user_posts = Post.objects.filter(author=request.user.id)
        posts = feed_posts
        form = PostForm()
        share_form = ShareForm()
        reply_form = CommentForm()

        context = {
            'post_list': posts,
            'form': form,
            'shareform': share_form,
            'reply_form':reply_form
        }

        return render(request, 'posts/post_list.html', context)

    def post(self, request, *args, **kwargs):
        # shows only posts from users that are followed
        feed_posts = Post.objects.filter(
            author__profile__followers__in=[request.user.id]
        ).order_by('-created_at')
        # user_posts = Post.objects.filter(author=request.user)
        posts = feed_posts
        form = PostForm(request.POST, request.FILES)
        files = request.FILES.getlist('image')
        share_form = ShareForm()

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()

            new_post.create_tags()

            for f in files:
                img = Image(image=f)
                img.save()
                new_post.image.add(img)

            new_post.save()

        context = {
            'post_list': posts,
            'form': form,
            'shareform': share_form,
        }

        return render(request, 'posts/post_list.html', context)

class PostDetail(SelectRelatedMixin,generic.DetailView):
    model = Post
    select_related = ('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm()
        share_form = ShareForm()
        reply_form = CommentForm()
        comments = Comment.objects.filter(post=post).order_by('-timestamp')
        context = {
            'post': post,
            'form': form,
            'comments': comments,
            'shareform':share_form,
            'reply_form':reply_form
        }
        return render(request, 'posts/post_detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        # form = PostForm(request.POST, request.FILES)
        form = CommentForm(request.POST)
        share_form = ShareForm()

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

            new_comment.create_tags()

        comments = Comment.objects.filter(post=post).order_by('-timestamp')

        notification = Notification.objects.create(notification_type=2, from_user=request.user, to_user=post.author, post=post)

        context = {
            'post': post,
            'form': form,
            'comments': comments,
            'shareform':share_form,
        }
        return render(request, 'posts/post_detail.html', context)

class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    model = Post
    fields = ('message','group','image')

    def get(self, request, *args, **kwargs):
        form = PostForm()

        context = {
            'form': form,
        }

        return render(request, 'posts/post_form.html', context)

    def post(self, request, *args, **kwargs):
        form = PostForm(request.POST, request.FILES)
        files = request.FILES.getlist('image')

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()

            new_post.create_tags()

            for f in files:
                img = Image(image=f)
                img.save()
                new_post.image.add(img)

            new_post.save()

        context = {
            'form': form,
        }

        return redirect('posts:all')

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    model = Post
    select_related = ('author','group')
    success_url = reverse_lazy('posts:all')

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.filter(author_id = self.request.user.id)

    def delete(self,*args,**kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

class EditPost(LoginRequiredMixin,SelectRelatedMixin,generic.UpdateView):
    model = Post
    select_related = ('author',)
    template_name = 'posts/post_edit.html'
    form_class = PostForm

    def post(self, request, pk, *args, **kwargs):
        form = PostForm(request.POST, request.FILES)
        files = request.FILES.getlist('image')

        if form.is_valid():
            post = Post.objects.get(pk=pk)
            form = PostForm(request.POST, instance=post)
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()

            new_post.create_tags()

            for f in files:
                img = Image(image=f)
                img.save()
                new_post.image.add(img)

            new_post.save()

        context = {
            'form': form,
        }

        return redirect('posts:all')

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('posts:single', kwargs={'pk': pk, 'username':self.request.user})

class AddLike(LoginRequiredMixin, generic.View):
    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        is_like = False
        for like in post.likes.all():
            if like == request.user:
                is_like = True
                break
        if not is_like:
            post.likes.add(request.user)
            notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=post.author, post=post)


        if is_like:
            post.likes.remove(request.user)

        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

class PostReplyView(LoginRequiredMixin, generic.View):
    def post(self, request, post_pk, *args, **kwargs):
        post = Post.objects.get(pk=post_pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

            new_comment.create_tags()

        notification = Notification.objects.create(notification_type=2, from_user=request.user, to_user=post.author, comment=new_comment)

        return redirect('posts:single', username=post.author, pk=post_pk)

class CommentReplyView(LoginRequiredMixin, generic.View):
    def post(self, request, post_pk, pk, *args, **kwargs):
        post = Post.objects.get(pk=post_pk)
        parent_comment = Comment.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.parent = parent_comment
            new_comment.save()

            new_comment.create_tags()

        notification = Notification.objects.create(notification_type=2, from_user=request.user, to_user=parent_comment.author, comment=new_comment)

        return redirect('posts:single', username=post.author, pk=post_pk)

class CommentDeleteView(LoginRequiredMixin,generic.DeleteView):
    model = Comment
    template_name = 'posts/comment_delete.html'

    def get_success_url(self):
        pk = self.kwargs['post_pk']
        return reverse_lazy('posts:single', kwargs={'pk': pk, 'username':self.request.user})

class AddCommentLike(LoginRequiredMixin, generic.View):
    def post(self, request, pk, *args, **kwargs):
        comment = Comment.objects.get(pk=pk)
        is_like = False
        for like in comment.likes.all():
            if like == request.user:
                is_like = True
                break
        if not is_like:
            comment.likes.add(request.user)
            notification = Notification.objects.create(notification_type=1, from_user=request.user, to_user=comment.author, comment=comment)

        if is_like:
            comment.likes.remove(request.user)
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)

class SharedPostView(generic.View):
    ''' View to handle post request when sharing a post,
    creates a new post with all the data and redirects back to post list'''
    def post(self, request, pk, *args, **kwargs):
        original_post = Post.objects.get(pk=pk)
        form = ShareForm(request.POST)

        if form.is_valid():
            new_post = Post(
                shared_body = self.request.POST.get('body'),
                message = original_post.message,
                author = original_post.author,
                created_at = original_post.created_at,
                shared_on = timezone.now(),

socialproject/posts/templates/posts/_post.html
{% load static %}

{% load bulma_tags %}

<!-- Post article -->
<article class="media pb-2">
  <!-- Poster details -->
  <figure class="media-left">
    <p class="image is-64x64 is-square">
      <a href="{% url 'accounts:profile' post.author.profile.pk %}"><img src="{{ post.author.profile.picture.url }}" alt="{{ post.author }}" class="is-rounded"></a>
    </p>
  </figure>

  <!-- Poster content -->
  <div class="media-content">
    <div class="content">

      <!-- Shared post -->
      {% if post.shared_user %}
      <div class="level">
        <a class="level-item level-right" href="{% url 'accounts:profile' post.shared_user.profile.pk %}">
          <img height="30" width="30" src="{{ post.shared_user.profile.picture.url }}" class="is-rounded"/>
        </a>
        <p class="post-text">
          <a class="text-primary post-link has-text-warning" href="{% url 'accounts:profile' post.shared_user.profile.pk %}">&nbsp&nbsp@{{ post.shared_user }}</a>
          shared this post on {{ post.shared_on|date:"j/n/y, f A"}}
          {% if post.shared_body %}
            and said: <em>{{ post.shared_body }}</em>
          {% endif %}
        </p>
      </div>
      {% endif %}

      <!-- Poster details -->
      <strong><a class="has-text-warning is-size-4" href="{% url 'accounts:profile' post.author.profile.pk %}">@{{post.author}}</a></strong>
      <small>
        <time class="time">
        <a class="has-text-warning" href="{% url 'posts:single' username=post.author pk=post.pk %}">&nbsp{{post.created_at|date:"M j, f A"}}</a>
        </time>
      </small>
      {% if post.group %}
      <a class="tag is-warning is-light" href="{% url 'groups:single' slug=post.group.slug %}" style="float:right;">{{post.group}}</a>
      {% endif %}
      <br>

      <!-- Post image (if) -->
      {% if post.image.count > 0 %}
        {% for img in post.image.all %}
          <img src="{{ img.image.url }}" class="post-image" />
        {% endfor %}
        <br>
      {% endif %}

      <!-- Post content -->
      <div class="post-body">
        <p>{{ post.message }}</p>
      </div>
    </div>

    <!-- Post menu -->
    <nav class="level is-mobile">
      <div class="level-left">

        <!-- Replies -->
        <a class="level-item has-text-warning">
          <span class="material-icons" onclick="commentReplyToggle('reply{{ post.pk }}')">reply</span>
        </a>

        <!-- Shares -->
        <a class="level-item has-text-warning">
          <span onclick="shareToggle('share{{ post.pk }}')" class="material-icons">share</span>
        </a>

        <!-- Likes -->
        <form class="level-item" method="POST" action="{% url 'posts:like' pk=post.pk %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ request.path }}">
            <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                {% if user in post.likes.all %}
                <a class="level-item has-text-warning">
                  <span class="material-icons">favorite</span>
                  <span class="level-item has-text-warning-light">&nbsp{{ post.likes.all.count }}</span>
                </a>
                {% else %}
                <a class="level-item has-text-warning">
                  <span class="material-icons">favorite_border</span>
                  <span class="level-item has-text-warning-light">&nbsp{{ post.likes.all.count }}</span>
                </a>
                {% endif %}
            </button>
        </form>

        <a class="level-item" href="{% url 'posts:single' username=post.author pk=post.pk %}">
          <span class="material-icons has-text-warning">mark_unread_chat_alt</span>
          <span class="level-item has-text-warning-light">&nbsp{{ post.comments.all.count }}</span>
        </a>

    </nav>

    <!-- Reply/Comment form (hidden) -->
    <div class="mt-3 mb-5 is-hidden is-reply" id="reply{{ post.pk }}">
        <form method="POST" action="{% url 'posts:post-reply' post.pk %}">
          {% csrf_token %}
          {{ reply_form }}
            <button class="button mt-3">Reply!</button>
        </form>
    </div>

    <!-- Share form (hidden) -->
    <div class="mt-3 mb-5 is-hidden is-share" id="share{{ post.pk }}">
        <form method="POST" action="{% url 'posts:share-post' post.pk %}">
          {% csrf_token %}
          {{ shareform }}
            <button class="button mt-3">Share!</button>
        </form>
    </div>

  </div>

  <!-- Delete post -->
  <div class="media-right">
    {% if request.user.is_superuser %}
      <a href="{% url 'posts:delete' pk=post.pk %}" title='delete' class="delete"></a>
    {% elif user.is_authenticated and post.author == request.user %}
      <a href="{% url 'posts:delete' pk=post.pk %}" title='delete' class="delete"></a>
    {% elif user.is_authenticated and post.shared_user == request.user %}
      <a href="{% url 'posts:delete' pk=post.pk %}" title='delete' class="delete"></a>
    {% endif %}
  </div>
</article>

<!-- Post Replies -->
<div class="pl-5">

  <!-- Parent comment -->
  {% for comment in comments %}
    {% if comment.is_parent %}
    <article class="media pb-2">
      <figure class="media-left">
        <a href="{% url 'accounts:profile' comment.author.profile.pk %}">
          <img class="image is-rounded" height="40" width="40" src="{{ comment.author.profile.picture.url }}" />
        </a>
      </figure>
      <div class="media-content">
        <div class="content">
          <strong>
            <a class="has-text-warning" href="{% url 'accounts:profile' comment.author.profile.pk %}">@{{ comment.author }}</a>
          </strong>
          <small>
            <time class="time">
              <a class="has-text-warning">&nbsp{{ comment.timestamp }}</a>
            </time>
          </small>
          <br>
          <div class="post-body">
            <p>{{ comment.comment }}</p>
          </div>
        </div>
        <nav class="level is-mobile">
          <div class="level-left">
            <a class="level-item has-text-warning">
              <span class="material-icons" onclick="commentReplyToggle('{{ comment.pk }}')">reply</span>
            </a>
            <form class="level-item" method="POST" action="{% url 'posts:comment-like' post.pk comment.pk%}">
              {% csrf_token %}
              <input type="hidden" name="next" value="{{ request.path }}">
              <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                {% if user in comment.likes.all %}
                <a class="level-item has-text-warning">
                  <span class="material-icons">favorite</span>
                  <span class="level-item has-text-warning-light">&nbsp{{ comment.likes.all.count }}</span>
                </a>
                {% else %}
                <a class="level-item has-text-warning">
                  <span class="material-icons">favorite_border</span>
                  <span class="level-item has-text-warning-light">&nbsp{{ comment.likes.all.count }}</span>
                </a>
                {% endif %}
              </button>
            </form>
          </nav>
          <div class="mt-3 mb-5 is-hidden" id="{{ comment.pk }}">
            <div class="col">
              <form method="POST" action="{% url 'posts:comment-reply' post.pk comment.pk %}">
                {% csrf_token %}
                {{ form | bulma }}
                <div class="d-grid gap-2">
                  <button class="button mt-3">Reply!</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="media-right">
          {% if request.user.is_superuser %}
            <a href="{% url 'posts:comment-delete' post.pk comment.pk %}" title='delete' class="delete"></a>
          {% elif user.is_authenticated and request.user == comment.author %}
            <a href="{% url 'posts:comment-delete' post.pk comment.pk %}" title='delete' class="delete"></a>
          {% endif %}
        </div>
    </article>

    <!-- Comment replies (child comment) -->
    <div class="pl-5 mb-5">
      {% for child_comment in comment.children %}
      <article class="media pb-2">
        <figure class="media-left">
          <a href="{% url 'accounts:profile' child_comment.author.profile.pk %}">
            <img class="image is-rounded" height="40" width="40" src="{{ child_comment.author.profile.picture.url }}" />
          </a>
        </figure>
        <div class="media-content">
          <div class="content">
            <strong>
              <a class="has-text-warning" href="{% url 'accounts:profile' child_comment.author.profile.pk %}">@{{ child_comment.author }}</a>
            </strong>
            <small>
              <time class="time">
                <a class="has-text-warning">&nbsp{{ child_comment.timestamp }}</a>
              </time>
            </small>
            <br>
            <div class="post-body">
              <p>{{ child_comment.comment }}</p>
            </div>
          </div>
          <nav class="level is-mobile">
            <div class="level-left">
              <form class="level-item" method="POST" action="{% url 'posts:comment-like' post.pk child_comment.pk%}">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button style="background-color: transparent; border: none; box-shadow: none;" type="submit">
                  {% if user in child_comment.likes.all %}
                  <a class="level-item has-text-warning">
                    <span class="material-icons">favorite</span>
                    <span class="level-item has-text-warning-light">&nbsp{{ child_comment.likes.all.count }}</span>
                  </a>
                  {% else %}
                  <a class="level-item has-text-warning">
                    <span class="material-icons">favorite_border</span>
                    <span class="level-item has-text-warning-light">&nbsp{{ child_comment.likes.all.count }}</span>
                  </a>
                  {% endif %}
                </button>
              </form>
            </nav>
          </div>
          <div class="media-right">
            {% if request.user.is_superuser %}
              <a href="{% url 'posts:comment-delete' post.pk child_comment.pk %}" title='delete' class="delete"></a>
            {% elif user.is_authenticated and request.user == child_comment.author %}
              <a href="{% url 'posts:comment-delete' post.pk child_comment.pk %}" title='delete' class="delete"></a>
            {% endif %}
          </div>
        </article>
        {% endfor %}
    </div>

    {% endif %}
  {% endfor %}

</div>

socialproject/posts/templates/posts/comment_delete.html
{% extends "posts/post_base.html" %}

{% block title %}<title>Plume - Comment Delete</title>{% endblock %}

{% block post_content %}
<h1 class="title has-text-light tricks pop-in">Are you sure you want to delete this comment?</h1>
<a href="{{request.META.HTTP_REFERER|escape}}" class="button mb-5">Return to Post</a>
<p>You are about to delete this comment, this cannot be undone.</p>
<form method="POST">
  {% csrf_token %}
  <div class="mt-5">
    <button type="submit" class="button">Delete</button>
  </div>
</form>
{% endblock %}

socialproject/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% load static %}

{% load bulma_tags %}

{% block title %}<title>Plume - @{{ post.author }}'s post</title>{% endblock %}

{% block post_content %}
<h1 class="title has-text-light">@{{ post.author }}'s post
  {% if request.user == post.author %}
  <a href="{% url 'posts:edit' post.pk %}"><i class="material-icons has-text-warning">edit</i></a>
  <a href="{% url 'posts:delete' post.pk %}"><i class="material-icons has-text-warning">delete</i></a>
  {% endif %}
</h1>

<div class="mt-3 column is-three-quarters">

  <!-- Singular post -->
  {% include "posts/_post.html" %}

</div>
{% endblock %}

socialproject/posts/templates/posts/post_form.html
{% extends "posts/post_base.html" %}

{% load bulma_tags %}
{% load static %}

{% block title %}<title>Plume - New Post</title>{% endblock %}

{% block post_content %}
<div class="columns is-vcentered">
  <div class="card column is-half p-5">
    <h1 class="title has-text-light tricks pop-in">Create a new post</h1>
    <form action="{% url 'posts:create' %}" method="post" enctype="multipart/form-data" class="column">
      {% csrf_token %}
      {{ form.message | bulma }}
      <div class="mb-3">
        {{ form.group | bulma }}
      </div>
      {{ form.image | bulma }}
      <input type="submit" value="Post!" class='button mt-5'>
    </form>
  </div>
  <div class="column is-half px-5 mx-5">
    <figure class="image">
      <img src="{% static 'images/pof-pof/Presentation.png' %}">
    </figure>
  </div>
</div>
{% endblock %}

socialproject/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% load bulma_tags %}
{% load static %}
{% load account %}

{% block title %}<title>Plume - My Feed</title>{% endblock %}

{% block pre_post_content %}
<h1 class="title has-text-light tricks pop-in">My feed</h1>
{% if request.user.is_authenticated %}
<p class="subtitle has-text-light mb-0">Welcome 👋 <strong><a class="has-text-warning" href="{% url 'accounts:profile' request.user.pk %}">@{{ user }}</a></strong>, here are posts from users you follow!</p>
{% endif %}

<!-- {% if confirmation %}
{% else %}
<p><i>An e-mail confirmation link has been sent to your email. Otherwise, please <a class="has-text-warning" href="{% url 'account_email' %}">issue a new e-mail confirmation request</a></i></p>
{% endif %} -->

<div class="pt-5 columns is-vcentered feed">

  <div class="card column is-half p-5 mb-5">
      <form method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.message|bulma }}
  				{{ form.image|bulma }}
          <button class="button my-3">Submit!</button>
      </form>
  </div>

  <div class="column is-half p-5 m-5">
    <figure class="image p-5 m-5">
      <img src="{% static 'images/pof-pof/Selfie.png' %}">
    </figure>
  </div>
</div>

{% endblock %}
{% block post_content %}
<div>
	{% for post in post_list %}
  {% include "posts/_post.html" %}
	{% endfor %}
</div>

<!-- Remember scroll position JS -->
<script type="text/javascript">
  let sidebar = document.querySelector(".sidebar");

  let tops = localStorage.getItem("sidebar-scroll");
  if (tops !== null) {
    sidebar.scrollTop = parseInt(top, 10);
  }

  window.addEventListener("beforeunload", () => {
    localStorage.setItem("sidebar-scroll", sidebar.scrollTop);
  });
</script>
{% endblock %}